config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

  get '/impressum', :to => 'pages#impressum', :as => 'impressum'
  get '/notes', :to => 'pages#notes', :as => 'notes'

  get '/h/:id', :to => 'houses#show', :as => 'house'
  put '/h/:id', :to => 'houses#update'
  patch '/h/:id', :to => 'houses#update'
  delete '/h/:id', :to => 'houses#destroy'

  devise_for :admins

  resources :houses, :except => [:show, :update, :destroy] do
      resources :pictures
      resources :bookings
  end

  put '/houses', :to => 'houses#activate'
  put '/houses/:house_id/pictures', :to => 'pictures#set_default'
  put '/houses/:house_id/bookings', :to => 'bookings#change_accepted'

  get '/list', :to => 'houses#f_index', :as => 'houses_list'

  get '/config/places', :to => 'places#edit', :as => 'edit_place'
  patch '/config/places', :to => 'places#update'
  put '/config/places', :to => 'places#update'

  get '/config/details', :to => 'details#edit', :as => 'edit_details'
  patch '/config/details', :to => 'details#update'
  put '/config/details', :to => 'details#update'

  get '/config/pages', :to => 'page_configs#edit', :as => 'edit_page_config'
  patch '/config/pages', :to => 'page_configs#update'
  put '/config/pages', :to => 'page_configs#update'

end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :location, counter_cache: true

	has_one :facility
	has_one :suitability
	has_one :pricing, :dependent => :destroy
	has_many :pictures, :dependent => :destroy
	has_many :bookings, :dependent => :destroy
	has_and_belongs_to_many :suits
	has_and_belongs_to_many :facilities

	accepts_nested_attributes_for :pricing, :pictures, :facilities, :suits

	geocoded_by :address
	after_validation :geocode

	after_update :change_houses_count

	def change_activate
		if self.activated?
			self.update_attributes(:activated => false)
		else
			if self.location
				self.update_attributes(:activated => true)
			else
				return false
			end
		end
	end

	def change_houses_count
		self.location.region.change_houses_count if self.location
	end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :edit, :create, :update, :destroy]
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :set_dates, only: [:show]

  respond_to :html

  def index
    @houses = []
  Region.all.order(:name).each do |region|
    region.locations.order(:name).each do |location|
			location.houses.order(:name).each do |house|
				@houses << house
			end
		end
	end
	House.all.where(location_id: nil).each do |house|
		@houses << house
	end
    respond_with(@houses)
  end

  def f_index
    @search = House.where(activated: true).search(params[:q])
    @houses = @search.result(distinct: true)
    @locations = Location.where(id: @houses.map(&:location_id).compact.uniq).order(:name)
    @regions = Region.where(id: @locations.map(&:region_id).compact.uniq).order(houses_count: :desc)
    @countries = Country.all.order(:name)
  end

  def activate
    @house = House.find(params[:h])
    if @house.change_activate
      flash[:notice] = "#{@house.name} wurde aktiviert/deaktiviert."
    else
      flash[:error] = "#{@house.name} konnte nicht aktiviert werden."
    end
    redirect_to houses_path
  end

  def show
    @hash = Gmaps4rails.build_markers(@house) do |house, marker|
      marker.lat house.latitude
      marker.lng house.longitude
    end
    @booking = @house.bookings.build
    respond_with(@house)
  end

  def edit
    gon.types = House.all.pluck(:htype)
  end

  def create
    @house = House.new(name: "new house")
    @pricing = @house.build_pricing
    @pricing.periods.build
    @pricing.costs.build
    @house.save
    flash[:notice] = "Ein neues Haus wurde angelegt."
    redirect_to edit_house_path(@house)
  end

  def update
    if @house.update(house_params)
      flash[:notice] = "Die Änderungen wurden gespeichert!"
      redirect_to houses_path
    else
      flash[:notice] = "Die Änderungen konnten nicht gespeichert werden."
      render :edit
    end
  end

  def destroy
    @house.destroy
    flash[:notice] = "Das Haus wurde erfolgreich gelöscht!"
    respond_with(@house)
  end

  private
    def set_house
      @house = House.find(params[:id])
    end

  def set_dates
    #disabled_dates = []
    @busy_dates = []
	  @closed_dates = []
	  @request_dates = []
	  @special_dates = []
    @start_dates = []
    @end_dates = []

  @house.pricing.periods.where(ptype: 'geschlossen').each do |p|
    if p.from && p.to
      (p.from..p.to).each do |d|
        # disabled_dates << d.to_s
        @closed_dates << d
      end
    end
  end

    @house.bookings.where(accepted: true).each do |b|
      @start_dates << b.start_date if b.start_date
      @end_dates << b.end_date if b.end_date
      if b.start_date && b.end_date
        (b.start_date+1..b.end_date-1).each do |d|
          #disabled_dates << d.to_s
          @busy_dates << d
        end
      end
    end
    #gon.dates = disabled_dates

	  @house.pricing.periods.where(ptype: "auf Anfrage").each do |p|
	    if p.from && p.to
        (p.from..p.to).each do |d|
  		    @request_dates << d
  	    end
      end
	  end

	  @house.pricing.periods.where(ptype: "Sonderangebot").each do |p|
	    if p.from && p.to
        (p.from..p.to).each do |d|
  		    @special_dates << d
  	    end
      end
	  end
  end

    def house_params
      params.require(:house).permit(:id, :name, :description, :location_id, :size, :n_people, :add_n_people, :htype, :movie_url, :address, :latitude, :longitude, :short_description,
	    :suit_ids => [],
      :facility_ids => [],
		pricing_attributes: [:id, :n_people, :surcharge_night, :surcharge_week, :house_id, :note,
		  periods_attributes: [:id, :from, :to, :min, :min_type, :cost_per_night, :cost_per_week, :cost_add_week, :season, :pricing_id, :ptype, :cost_add_person, :cost_add_person_week, :_destroy],
	      costs_attributes: [:id, :name, :ctype, :amount, :optional, :pricing_id, :_destroy]
		],
		pictures_attributes: [:id, :name, :house_id, :image, :_destroy],
		pictures_attributes: [:id, :house_id, :internet, :tv, :pool, :garden, :terrasse, :grill, :balcony, :washingmachine, :dishwasher, :babybed, :_destroy]
	  )
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_booking_form.html.erb
<%= simple_form_for [@house,@booking], :html => { :class => 'form-vertical' } do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.input :gender, :as => :radio_buttons, collection: ['Frau', 'Herr'], label: "Anrede" %>
        <div class="row">
          <div class="col-md-6"><%= f.input :lastname, label: "Nachname", required: true %></div>
          <div class="col-md-6"><%= f.input :firstname, label: "Vorname", required: true %></div>
        </div><br>
        <div class="row">
          <div class="col-md-6"><%= f.input :email, required: true %></div>
          <div class="col-md-6"><%= f.input :phone, label: "Telefon" %></div>
        </div><br>

        <div class="form-group">
          <label class="string optional control-label required" for="booking_lastname">Zeitraum</label><br>
          <input id="daterange" name="daterange">
          <br><%= f.hidden_field :start_date %>
          <br><%= f.hidden_field :end_date %>

        </div><br>

        <div class='row'>
            <div class='col-md-12'>
              <%= f.input :message, label: "Mitteilung", :as => :text, :input_html => { :rows => 10, :style => 'resize: none;' } %>
            </div>
        </div>
        <br>
        <div class="center-block">
          <div class="form-group text-center">
            <%= f.button :submit, "Abschicken", :class => 'btn-primary' %> oder
            <%= link_to "Abbrechen", :back, :class => 'btn btn-default' %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/houses/_houses.html+mobile.erb
<% @countries.each do |c| %>
  <% @regions.where(country_id: c.id).each do |r| %>


    <h4 style="margin-bottom:3px"><%= r.name %> (<%= c.name.upcase %>)</h4>
    <hr style="margin-top:3px;margin-bottom:3px; border-color:black">


    <% @locations.where(region_id: r.id).each do |l| %>
      <% @houses.where(location_id: l.id).each do |h| %>


         <%= link_to house_path(h), data: {no_turbolink: true } do %>
          <div class="jumbotron color2 list" style="margin-bottom: 3px;">

            <div class="row">
              <div class="col-xs-7">
                <% if h.pictures.where(default_pic: true).count > 0 %>
                  <%= image_tag h.pictures.where(default_pic: true).first.image_url(:thumb), width: "100%" %>
                <% end %>
              </div>
              <div class="col-xs-5" style="padding-left:0;">

                <h4 style="margin-top: 0px; margin-bottom: 0px;"><%= h.name %>(<%= h.location.name %>)</h4><hr class="small">

                <div class="content2">
                  <%= "#{h.n_people} Personen" if h.n_people %>
                  <%= "(max. #{h.add_n_people})" if h.add_n_people %>
                  <% if (h.n_people && h.size) %>&bull;<br><% end %>
                  <%= "#{h.size} m²" if h.size %>
                </div>

                <div class="btn btn-default btn-xs">
                  <span class="glyphs" data-toggle="tooltip" data-html="true" data-placement="top" title="<% h.suits.where(activated:'Ja').each do |s| %><li style='margin-left:20px;'><%= s.name %></li><% end %>">
                  Geeignet für</span>
                </div>
                <div class="btn btn-default btn-xs">
                  <span class="glyphs" data-toggle="tooltip" data-html="true" data-placement="top" title="<% h.facilities.where(activated:'Ja').each do |f| %><li style='margin-left:20px;'><%= f.name %></li><% end %>">
                  Ausstattung</span>
                </div>

                <div style="font-size: 1.2em;">
                  <% if h.pricing.periods.where(ptype: ['geöffnet', 'Sonderangebot']).where('"to" >= ?', Date.today).first %>
                    ab
                    <%= h.pricing.periods.where(ptype: ['geöffnet', 'Sonderangebot']).where('"to" >= ?', Date.today).order(:cost_per_week).first.cost_per_week %>
                    €/Woche
                  <% end %>
                </div>
              </div>
            </div>


            <div class="row">
              <div class="col-xs-12">
                <hr style="margin:3px 0 3px 0;">
                <div class="content-mobile">
                  <%= h.short_description.html_safe if h.short_description %>
                </div>
              </div>
            </div>

          </div>
        <% end %>


      <% end %>
    <% end %>


    <hr style="margin-top:3px;margin-bottom:20px; border-color:black">


  <% end %>
<% end %>

app/views/houses/_houses.html.erb
<% @countries.each do |c| %>
  <% @regions.where(country_id: c.id).each do |r| %>


    <h4 style="margin-bottom:3px"><%= r.name %> (<%= c.name.upcase %>)</h4>
    <hr style="margin-top:3px;margin-bottom:3px; border-color:black">


    <% @locations.where(region_id: r.id).each do |l| %>
      <% @houses.where(location_id: l.id).each do |h| %>


         <%= link_to house_path(h), data: {no_turbolink: true } do %>
          <div class="jumbotron color2 list" style="margin-bottom: 3px;">
            <div class="row">
              <div class="col-md-4">
                <% if h.pictures.where(default_pic: true).count > 0 %>
                  <%= image_tag h.pictures.where(default_pic: true).first.image_url(:thumb), size: "260x195" %>
                <% end %>
              </div>
              <div class="col-md-8">
                <h4 style="margin-top: 0px; margin-bottom: 0px;"><%= h.name %> (<%= h.location.name %>)</h4><hr class="small">
                <div class="content">
                  <%= h.short_description.html_safe if h.short_description %>
                </div><hr style="margin:3px 0 3px 0;">
                <div class="content2">
                  <%= "#{h.n_people} Personen" if h.n_people %>
                  <%= "(max. #{h.add_n_people})" if h.add_n_people %>
                  <% if (h.n_people && h.size) %>&bull;<% end %>
                  <%= "#{h.size} m²" if h.size %>
                </div>
                <div class="left">
                  <div class="btn btn-default">
                    <span class="glyphs" data-toggle="tooltip" data-html="true" data-placement="top" title="<% h.suits.where(activated:'Ja').each do |s| %><li style='margin-left:20px;'><%= s.name %></li><% end %>">
                    Geeignet für</span>
                  </div>
                  <div class="btn btn-default">
                    <span class="glyphs" data-toggle="tooltip" data-html="true" data-placement="top" title="<% h.facilities.where(activated:'Ja').each do |f| %><li style='margin-left:20px;'><%= f.name %></li><% end %>">
                    Ausstattung</span>
                  </div>
                </div>

                <div class="right">
                  <div style="font-size: 1.2em;">
                    <% if h.pricing.periods.where(ptype: ['geöffnet', 'Sonderangebot']).where('"to" >= ?', Date.today).first %>
                      ab
                      <%= h.pricing.periods.where(ptype: ['geöffnet', 'Sonderangebot']).where('"to" >= ?', Date.today).order(:cost_per_week).first.cost_per_week %>
                      €/Woche

                    <% end %>
                  </div>
                </div>
                </p>
              </div>
            </div>
          </div>
        <% end %>


      <% end %>
    <% end %>


    <hr style="margin-top:3px;margin-bottom:20px; border-color:black">


  <% end %>
<% end %>

app/views/houses/edit.html.erb
<%- model_class = House -%>
<div class="page-header">
  <h2>"<%= @house.name %>" bearbeiten:</h2>
</div>
<%= render :partial => 'form' %>

app/views/houses/f_index.html+mobile.erb
<div class="row">
  <div class="col-xs-12">

    <div class="jumbotron color1 lowpad" style="font-size:0.85em">
      <h4 style="text-align: center;margin:0;">Suchkriterien</h4><hr class="small">

        <%= search_form_for @search, url: houses_list_path, :builder => SimpleForm::FormBuilder, :id => 'houses_search' do |f| %>

            <label class="string optional control-label" for="booking_lastname">Regionen/Ferienorte</label><br>
            <div class="checkbox">
              <% Country.where(id: House.where(activated:true).map(&:location).map(&:region).map(&:country).compact.uniq).each do |c| %>
                <div style="text-decoration: underline;"><%= c.name %></div>
                <% Region.where(country_id: c.id).where(id: House.where(activated:true).map(&:location).map(&:region_id).compact.uniq).each do |r| %>
                  <label class="checkbox-inline">
                    <%= check_box_tag('q[location_region_id_in][]', r.id) %>
                    <%= r.name %>
                  </label><br>

                    <% r.locations.order(:name).each do |l| %>
                      <% if l.houses.count > 0 %>
                        <label class="checkbox-inline" style="margin-left: 10px;">
                          <%= check_box_tag('q[location_name_in][]', l.name) %>
                          <%= l.name %>
                        </label><br>
                      <% end %>
                    <% end %>

                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Personen (max.)</label><br>

            <div class="form-group">
              <%= f.search_field :add_n_people_gteq, class: 'form-control', size: 1 %>
            </div>

            <!--
            <div class="checkbox">
                <% House.where(activated: true).order(:n_people).pluck(:n_people).to_a.uniq.compact.each do |n| %>
                  <label class="checkbox-inline" style="margin-right:2px;">
                    <%= check_box_tag('q[n_people_eq_any][]', n) %><%= n %>
                  </label>
                <% end %>
            </div> -->
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Ausstattung</label><br>
            <div class="checkbox">
              <% Facility.where(activated:"Ja").each do |f| %>
                <% if f.name != (nil || "") %>
                  <label>
                    <%= check_box_tag('q[facilities_id_eq]', f.id) %> <%= f.name %>
                  </label><br>
                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Geeignet für</label>
            <div class="checkbox">
              <% Suit.where(activated:"Ja").each do |s| %>
                <% if s.name != (nil || "") %>
                  <label>
                    <%= check_box_tag('q[suits_id_eq]', s.id) %> <%= s.name %>
                  </label><br>
                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Objekttyp</label>
            <div class="checkbox">
                <% House.where(activated: true).pluck(:htype).compact.uniq.each do |t| %>
                  <% if t != "" %>
                    <label>
                      <%= check_box_tag('q[htype_eq_any][]', t) %> <%= t %>
                    </label><br>
                  <% end %>
                <% end %>
            </div>
            <hr class="small">
            <div class="center-block">
                <div class="form-group text-center">
                  <button class="btn btn-default" id="selectAll">Alle Filter entfernen</button>
                </div>
            </div>
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12" id="houses">
    <%= render 'houses' %>
  </div>
</div>

app/views/houses/f_index.html+tablet.erb
<div class="row">
  <div class="col-sm-4">

    <div class="jumbotron color1 lowpad" style="font-size:0.85em">
      <h4 style="text-align: center;margin:0;">Suchkriterien</h4><hr class="small">

        <%= search_form_for @search, url: houses_list_path, :builder => SimpleForm::FormBuilder, :id => 'houses_search' do |f| %>

            <label class="string optional control-label" for="booking_lastname">Regionen/Ferienorte</label><br>
            <div class="checkbox">
              <% Country.where(id: House.where(activated:true).map(&:location).map(&:region).map(&:country).compact.uniq).each do |c| %>
                <div style="text-decoration: underline;"><%= c.name %></div>
                <% Region.where(country_id: c.id).where(id: House.where(activated:true).map(&:location).map(&:region_id).compact.uniq).each do |r| %>
                  <label class="checkbox-inline">
                    <%= check_box_tag('q[location_region_id_in][]', r.id) %>
                    <%= r.name %>
                  </label><br>

                    <% r.locations.order(:name).each do |l| %>
                      <% if l.houses.count > 0 %>
                        <label class="checkbox-inline" style="margin-left: 10px;">
                          <%= check_box_tag('q[location_name_in][]', l.name) %>
                          <%= l.name %>
                        </label><br>
                      <% end %>
                    <% end %>

                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Personen (max.)</label><br>

            <div class="form-group">
              <%= f.search_field :add_n_people_gteq, class: 'form-control', size: 1 %>
            </div>

            <!--
            <div class="checkbox">
                <% House.where(activated: true).order(:n_people).pluck(:n_people).to_a.uniq.compact.each do |n| %>
                  <label class="checkbox-inline" style="margin-right:2px;">
                    <%= check_box_tag('q[n_people_eq_any][]', n) %><%= n %>
                  </label>
                <% end %>
            </div> -->
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Ausstattung</label><br>
            <div class="checkbox">
              <% Facility.where(activated:"Ja").each do |f| %>
                <% if f.name != (nil || "") %>
                  <label>
                    <%= check_box_tag('q[facilities_id_eq]', f.id) %> <%= f.name %>
                  </label><br>
                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Geeignet für</label>
            <div class="checkbox">
              <% Suit.where(activated:"Ja").each do |s| %>
                <% if s.name != (nil || "") %>
                  <label>
                    <%= check_box_tag('q[suits_id_eq]', s.id) %> <%= s.name %>
                  </label><br>
                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Objekttyp</label>
            <div class="checkbox">
                <% House.where(activated: true).pluck(:htype).compact.uniq.each do |t| %>
                  <% if t != "" %>
                    <label>
                      <%= check_box_tag('q[htype_eq_any][]', t) %> <%= t %>
                    </label><br>
                  <% end %>
                <% end %>
            </div>
            <hr class="small">
            <div class="center-block">
                <div class="form-group text-center">
                  <button class="btn btn-default" id="selectAll">Alle Filter entfernen</button>
                </div>
            </div>
      <% end %>


    </div>
  </div>

  <div class="col-sm-8" id="houses">
    <%= render 'houses' %>
  </div>

</div>

app/views/houses/f_index.html.erb
<div class="row">
  <div class="col-md-3">

    <div class="jumbotron color1 lowpad" style="font-size:0.85em">
      <h4 style="text-align: center;margin:0;">Suchkriterien</h4><hr class="small">

        <%= search_form_for @search, url: houses_list_path, :builder => SimpleForm::FormBuilder, :id => 'houses_search' do |f| %>

            <label class="string optional control-label" for="booking_lastname">Regionen/Ferienorte</label><br>
            <div class="checkbox">
              <% Country.where(id: House.where(activated:true).map(&:location).map(&:region).map(&:country).compact.uniq).each do |c| %>
                <div style="text-decoration: underline;"><%= c.name %></div>
                <% Region.where(country_id: c.id).where(id: House.where(activated:true).map(&:location).map(&:region_id).compact.uniq).each do |r| %>
                  <label class="checkbox-inline">
                    <%= check_box_tag('q[location_region_id_in][]', r.id) %>
                    <%= r.name %>
                  </label><br>

                    <% r.locations.order(:name).each do |l| %>
                      <% if l.houses.count > 0 %>
                        <label class="checkbox-inline" style="margin-left: 10px;">
                          <%= check_box_tag('q[location_name_in][]', l.name) %>
                          <%= l.name %>
                        </label><br>
                      <% end %>
                    <% end %>

                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Personen (max.)</label><br>

            <div class="form-group">
              <%= f.search_field :add_n_people_gteq, class: 'form-control', size: 1 %>
            </div>

            <!--
            <div class="checkbox">
                <% House.where(activated: true).order(:n_people).pluck(:n_people).to_a.uniq.compact.each do |n| %>
                  <label class="checkbox-inline" style="margin-right:2px;">
                    <%= check_box_tag('q[n_people_eq_any][]', n) %><%= n %>
                  </label>
                <% end %>
            </div> -->
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Ausstattung</label><br>
            <div class="checkbox">
              <% Facility.where(activated:"Ja").each do |f| %>
                <% if f.name != (nil || "") %>
                  <label>
                    <%= check_box_tag('q[facilities_id_eq]', f.id) %> <%= f.name %>
                  </label><br>
                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Geeignet für</label>
            <div class="checkbox">
              <% Suit.where(activated:"Ja").each do |s| %>
                <% if s.name != (nil || "") %>
                  <label>
                    <%= check_box_tag('q[suits_id_eq]', s.id) %> <%= s.name %>
                  </label><br>
                <% end %>
              <% end %>
            </div>
            <hr class="small">

            <label class="string optional control-label" for="booking_lastname">Objekttyp</label>
            <div class="checkbox">
                <% House.where(activated: true).pluck(:htype).compact.uniq.each do |t| %>
                  <% if t != "" %>
                    <label>
                      <%= check_box_tag('q[htype_eq_any][]', t) %> <%= t %>
                    </label><br>
                  <% end %>
                <% end %>
            </div>
            <hr class="small">
            <div class="center-block">
                <div class="form-group text-center">
                  <button class="btn btn-default" id="selectAll">Alle Filter entfernen</button>
                </div>
            </div>
      <% end %>


    </div>
  </div>

  <div class="col-md-9" id="houses">
    <%= render 'houses' %>
  </div>

</div>

app/views/houses/f_index.js.erb
$("#houses").html("<%= escape_javascript(render("houses")) %>");
$('[data-toggle="tooltip"]').tooltip();

app/views/houses/index.html.erb
<%- model_class = House -%>
<div class="page-header">
  <h1>Häuserliste</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Ort</th>
      <th>Region</th>
      <th>Buchungen</th>
      <th>Aktiv?</th>
      <th>Letzte Bearbeitung</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @houses.each do |house| %>
          <tr>
              <td><%= house.name %></td>
              <td><%= house.location.name if house.location_id %></td>
              <td><%= house.location.region.name if house.location_id %></td>
              <td><%= link_to "#{house.bookings.where(accepted: false).count} (#{house.bookings.count})", house_bookings_path(house), :class => "btn btn-xs btn-default" %></td>
              <td>
                <% if house.activated? %>
                    <span class="label label-success">Ja</span> (<%= link_to "deaktivieren", { :controller => 'houses', :action => 'activate', :h => house.id }, { :method => :put } %>)
                <% else %>
                    <span class="label label-danger">Nein</span> (<%= link_to "aktivieren", { :controller => 'houses', :action => 'activate', :h => house.id }, { :method => :put } %>)
                <% end %>
              </td>
            <td><%=l house.updated_at, format: :short %></td>
            <td>
              <%= link_to house_path(house), :class => 'btn btn-xs btn-primary', :title => "Anzeigen" do %>
                  <%= glyph 'search' %>
              <%- end -%>
              <%= link_to house_pictures_path(house), :class => 'btn btn-xs btn-default', :title => "Bilder" do %>
                  <%= glyph 'picture' %>
              <% end %>
              <%= link_to edit_house_path(house), :class => 'btn btn-xs btn-warning', :title => "Bearbeiten", data: {no_turbolink: true } do %>
                  <%= glyph 'pencil' %>
              <% end %>
              <%= link_to house_path(house), :method => :delete, :data => { :confirm => 'Sicher?' }, :class => 'btn btn-xs btn-danger', :title => "Löschen" do %>
                  <%= glyph 'remove' %>
              <% end %>
            </td>
          </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to houses_path, method: :post, :class => 'btn btn-primary', :title => 'Haus hinzufügen' do %>
    <%= glyph 'plus' %> Haus hinzufügen
<% end %>

<%= link_to edit_place_path, :class => 'btn btn-default', :title => 'Länder/Regionen bearbeiten' do %>
    <%= glyph 'pencil' %> Länder/Regionen/Orte bearbeiten
<% end %>

<%= link_to edit_details_path, :class => 'btn btn-default', :title => 'Ausstattung/Eignung bearbeiten' do %>
    <%= glyph 'pencil' %> Ausstattung/Eignung bearbeiten
<% end %>

<%= link_to edit_page_config_path, :class => 'btn btn-default', :title => 'Texte bearbeiten', data: {no_turbolink: true } do %>
    <%= glyph 'pencil' %> Texte bearbeiten
<% end %>

<%= link_to edit_admin_registration_path, :class => 'btn btn-default', :title => 'Adminprofil bearbeiten' do %>
    <%= glyph 'pencil' %> Adminprofil bearbeiten
<% end %>

app/views/houses/new.html.erb
<%- model_class = House -%>
<div class="page-header">
  <h2>"<%= @house.name %>" bearbeiten:</h2>
</div>
<%= render :partial => 'form' %>