config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

  get '/impressum', :to => 'pages#impressum', :as => 'impressum'
  get '/notes', :to => 'pages#notes', :as => 'notes'

  get '/h/:id', :to => 'houses#show', :as => 'house'
  put '/h/:id', :to => 'houses#update'
  patch '/h/:id', :to => 'houses#update'
  delete '/h/:id', :to => 'houses#destroy'

  devise_for :admins

  resources :houses, :except => [:show, :update, :destroy] do
      resources :pictures
      resources :bookings
  end

  put '/houses', :to => 'houses#activate'
  put '/houses/:house_id/pictures', :to => 'pictures#set_default'
  put '/houses/:house_id/bookings', :to => 'bookings#change_accepted'

  get '/list', :to => 'houses#f_index', :as => 'houses_list'

  get '/config/places', :to => 'places#edit', :as => 'edit_place'
  patch '/config/places', :to => 'places#update'
  put '/config/places', :to => 'places#update'

  get '/config/details', :to => 'details#edit', :as => 'edit_details'
  patch '/config/details', :to => 'details#update'
  put '/config/details', :to => 'details#update'

  get '/config/pages', :to => 'page_configs#edit', :as => 'edit_page_config'
  patch '/config/pages', :to => 'page_configs#update'
  put '/config/pages', :to => 'page_configs#update'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable,  and :omniauthable
  devise :database_authenticatable, :rememberable, :timeoutable, :registerable

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :house

  validates :start_date, :end_date, :firstname, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


  def change_accepted
    if self.accepted?
	    self.update_attributes(:accepted => false)
	 else
	    self.update_attributes(:accepted => true)
	 end
  end

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :pricing
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions, :dependent => :destroy
	belongs_to :place
	accepts_nested_attributes_for :regions
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_many :suits, :dependent => :destroy
  has_many :facilities, :dependent => :destroy
  accepts_nested_attributes_for :suits, :facilities, :allow_destroy => true
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :detail
	has_and_belongs_to_many :houses
  accepts_nested_attributes_for :houses
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :location, counter_cache: true

	has_one :facility
	has_one :suitability
	has_one :pricing, :dependent => :destroy
	has_many :pictures, :dependent => :destroy
	has_many :bookings, :dependent => :destroy
	has_and_belongs_to_many :suits
	has_and_belongs_to_many :facilities

	accepts_nested_attributes_for :pricing, :pictures, :facilities, :suits

	geocoded_by :address
	after_validation :geocode

	after_update :change_houses_count

	def change_activate
		if self.activated?
			self.update_attributes(:activated => false)
		else
			if self.location
				self.update_attributes(:activated => true)
			else
				return false
			end
		end
	end

	def change_houses_count
		self.location.region.change_houses_count if self.location
	end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :houses
  belongs_to :region
  accepts_nested_attributes_for :houses
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :page_config
end

app/models/page_config.rb
class PageConfig < ActiveRecord::Base
  has_many :pages
  accepts_nested_attributes_for :pages
end

app/models/period.rb
class Period < ActiveRecord::Base
	belongs_to :pricing
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :house
	mount_uploader :image, ImageUploader
	crop_uploaded :image

	def change_to_def
		self.house.pictures.each do |p|
			p.update_attribute(:default_pic, false)
		end
		self.update_attribute(:default_pic, true)
	end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :countries, :dependent => :destroy

  accepts_nested_attributes_for :countries
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
	has_many :periods, :dependent => :destroy
	has_many :costs, :dependent => :destroy
	belongs_to :house
	accepts_nested_attributes_for :periods, :costs, :allow_destroy => true
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :locations
	belongs_to :country
	accepts_nested_attributes_for :locations

  def change_houses_count
    cnt = 0
    self.locations.each do |l|
      cnt += l.houses_count
    end
    self.update_attributes(:houses_count => cnt)
  end

end

app/models/suit.rb
class Suit < ActiveRecord::Base
  belongs_to :detail
  has_and_belongs_to_many :houses
  accepts_nested_attributes_for :houses
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :edit, :update, :destroy, :new]
  before_action :set_house
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bookings = @house.bookings
    respond_with(@house, @bookings)
  end

  def show
    respond_with(@booking)
  end

  def new
    @booking = @house.bookings.build
    respond_with(@house,@booking)
  end

  def edit
  end

  def change_accepted
	@booking = Booking.find(params[:b])
	@booking.change_accepted
	redirect_to house_bookings_path
  end

  def create
    @booking = @house.bookings.build(booking_params)
    if @booking.save
      flash[:notice] = "Die Buchungsanfrage wurde erfolgreich erstellt!"
      if admin_signed_in?
        redirect_to house_bookings_path(@house)
      else
        redirect_to houses_list_path
      end
    else
      redirect_to @house, :flash => { :error => "Es ist ein Fehler aufgetreten!" }
    end
  end

  def update
    if @booking.update(booking_params)
      flash[:notice] = "Die Änderungen wurden gespeichert!"
      redirect_to house_bookings_path(@house)
    else
      flash[:error] = "Die Änderungen konnten nicht gespeichert werden!"
      redirect_to :back
    end
  end

  def destroy
    @booking.destroy
    flash[:notice] = "Die Buchung wurde erfolgreich gelöscht!"
    redirect_to house_bookings_path(@house)
  end

  private
    def set_house
      @house = House.find(params[:house_id])
    end

    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :lastname, :firstname, :house_id, :accepted, :message, :phone, :gender, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/facilites_helper.rb
module FacilitesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@house,@booking], :html => { :class => 'form-vertical' } do |f| %>

    <div class='row'>
      <div class='col-md-12'>
        <%= f.input :gender, :as => :radio_buttons, collection: ['Frau', 'Herr'], label: "Anrede" %>
        <div class="row">
          <div class="col-md-6"><%= f.input :lastname, label: "Nachname", required: true %></div>
          <div class="col-md-6"><%= f.input :firstname, label: "Vorname", required: true %></div>
        </div><br>
        <div class="row">
          <div class="col-md-6"><%= f.input :email, required: true %></div>
          <div class="col-md-6"><%= f.input :phone, label: "Telefon" %></div>
        </div><br>

        <div class="form-group">
          <label class="string optional control-label required" for="booking_lastname">Zeitraum</label><br>
          <input id="daterange" name="daterange">
          <br><%= f.hidden_field :start_date %>
          <br><%= f.hidden_field :end_date %>

        </div><br>

        <div class='row'>
            <div class='col-md-12'>
              <%= f.input :message, label: "Mitteilung", :as => :text, :input_html => { :rows => 10, :style => 'resize: none;' } %>
            </div>
        </div>
        <br>
        <div class="center-block">
          <div class="form-group text-center">
            <%= f.button :submit, "Abschicken", :class => 'btn-primary' %> oder
            <%= link_to "Abbrechen", :back, :class => 'btn btn-default' %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="page-header">
  <h1>Buchung #<%= @booking.id %> vom Haus "<%= @booking.house.name %>" bearbeiten</h1>
</div>

<%= render 'form' %>

app/views/bookings/index.html.erb
<%- model_class = Booking -%>

<div class="page-header">
  <h3>Buchungsanfragen für "<%= @house.name %>"</h3>
</div>


<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#open" aria-controls="open" role="tab" data-toggle="tab">Offen</a></li>
  <li role="presentation"><a href="#accepted" aria-controls="accepted" role="tab" data-toggle="tab">Angenommen</a></li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="open">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Start</th>
          <th>Ende</th>
          <th>Nachname</th>
          <th>Email</th>
          <th>Datum</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.where(accepted: false).order(:created_at).each do |booking| %>
          <tr>
            <td><%= booking.id %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= booking.lastname %></td>
            <td><%= booking.email %></td>
            <td><%=l booking.created_at, format: :short %></td>
			<td>
			  <%= link_to "aktivieren", { :controller => 'bookings', :action => 'change_accepted', :b => booking.id }, { :method => :put, :class => 'btn btn-xs btn-success' } %>
			</td>
            <td>
              <%= link_to house_booking_path(@house,booking), :class => 'btn btn-xs btn-primary', :title => "Anzeigen" do %>
                <%= glyph 'search' %>
              <%- end -%>
              <%= link_to edit_house_booking_path(@house,booking), :class => 'btn btn-xs btn-warning', :title => "Bearbeiten" do %>
                <%= glyph 'pencil' %>
              <%- end -%>
              <%= link_to house_booking_path(@house,booking), :method => :delete, :data => { :confirm => "Sicher?" }, :class => 'btn btn-xs btn-danger', :title => "Löschen" do %>
                <%= glyph 'remove' %>
              <%- end -%>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div role="tabpanel" class="tab-pane fade" id="accepted">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>ID</th>
        <th>Start</th>
        <th>Ende</th>
        <th>Nachname</th>
        <th>Email</th>
        <th>Datum</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @bookings.where(accepted: true).order(:created_at).each do |booking| %>
          <tr>
            <td><%= booking.id %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= booking.lastname %></td>
            <td><%= booking.email %></td>
            <td><%=l booking.created_at, format: :short %></td>
            <td>
			  <%= link_to "deaktivieren", { :controller => 'bookings', :action => 'change_accepted', :b => booking.id }, { :method => :put, :class => 'btn btn-xs btn-danger' } %>
			</td>
			<td>
              <%= link_to house_booking_path(@house,booking), :class => 'btn btn-xs btn-primary', :title => "Anzeigen" do %>
                  <%= glyph 'search' %>
              <%- end -%>
              <%= link_to edit_house_booking_path(@house,booking), :class => 'btn btn-xs btn-warning', :title => "Bearbeiten" do %>
                <%= glyph 'pencil' %>
              <%- end -%>

              <%= link_to house_booking_path(@house,booking), :method => :delete, :data => { :confirm => "Sicher?" }, :class => 'btn btn-xs btn-danger', :title => "Löschen" do %>
                  <%= glyph 'remove' %>
              <%- end -%>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to new_house_booking_path(@house), :title => "Neue Buchung", :class => 'btn btn-primary' do %>
    <%= glyph 'plus' %> Buchung hinzufügen
<% end %>

<%= link_to "Zurück", houses_path, :class => 'btn btn-default' %>

app/views/bookings/new.html.erb
<div class="page-header">
  <h1>Neue Buchung für das Haus "<%= @booking.house.name %>" erstellen</h1>
</div>

<%= render 'form' %>

app/views/bookings/show.html.erb
<div class="page-header">
  <h1>Buchung #<%= @booking.id %> vom Haus "<%= @booking.house.name %>"</h1>
</div>

<div class="fieldset">
  <dl>
    <div class="row">
      <div class="col-md-6">
        <dt class="label label-default">Anrede</dt>
        <dd><pre class="prettyprint"><%= @booking.gender %></pre></dd>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <dt class="label label-default">Nachname</dt>
        <dd><pre class="prettyprint"><%= @booking.lastname %></pre></dd>
      </div>
      <div class="col-md-6">
        <dt class="label label-default">Vorname</dt>
        <dd><pre class="prettyprint"><%= @booking.firstname %></pre></dd>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <dt class="label label-default">Start</dt>
        <dd><pre class="prettyprint"><%= @booking.start_date %></pre></dd>
      </div>
      <div class="col-md-6">
        <dt class="label label-default">Ende</dt>
        <dd><pre class="prettyprint"><%= @booking.end_date %></pre></dd>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <dt class="label label-default">Email</dt>
        <dd><pre class="prettyprint"><%= @booking.email %></pre></dd>
      </div>
      <div class="col-md-6">
        <dt class="label label-default">Telefon</dt>
        <dd><pre class="prettyprint"><%= @booking.phone %></pre></dd>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <dt class="label label-default">Angenommen?</dt>
        <dd><pre class="prettyprint"><% if @booking.accepted? %> Ja <% else %> Nein <% end %></pre></dd>
      </div>
      <div class="col-md-6">
        <dt class="label label-default">Datum</dt>
        <dd><pre class="prettyprint"><%= @booking.created_at %></pre></dd>
      </div>
    </div>

  </dl>
</div>



<%= link_to "Zurück", :back, :class => 'btn btn-default' %>