config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

  get '/impressum', :to => 'pages#impressum', :as => 'impressum'
  get '/notes', :to => 'pages#notes', :as => 'notes'

  get '/h/:id', :to => 'houses#show', :as => 'house'
  put '/h/:id', :to => 'houses#update'
  patch '/h/:id', :to => 'houses#update'
  delete '/h/:id', :to => 'houses#destroy'

  devise_for :admins

  resources :houses, :except => [:show, :update, :destroy] do
      resources :pictures
      resources :bookings
  end

  put '/houses', :to => 'houses#activate'
  put '/houses/:house_id/pictures', :to => 'pictures#set_default'
  put '/houses/:house_id/bookings', :to => 'bookings#change_accepted'

  get '/list', :to => 'houses#f_index', :as => 'houses_list'

  get '/config/places', :to => 'places#edit', :as => 'edit_place'
  patch '/config/places', :to => 'places#update'
  put '/config/places', :to => 'places#update'

  get '/config/details', :to => 'details#edit', :as => 'edit_details'
  patch '/config/details', :to => 'details#update'
  put '/config/details', :to => 'details#update'

  get '/config/pages', :to => 'page_configs#edit', :as => 'edit_page_config'
  patch '/config/pages', :to => 'page_configs#update'
  put '/config/pages', :to => 'page_configs#update'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable,  and :omniauthable
  devise :database_authenticatable, :rememberable, :timeoutable, :registerable

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :house

  validates :start_date, :end_date, :firstname, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


  def change_accepted
    if self.accepted?
	    self.update_attributes(:accepted => false)
	 else
	    self.update_attributes(:accepted => true)
	 end
  end

end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :pricing
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions, :dependent => :destroy
	belongs_to :place
	accepts_nested_attributes_for :regions
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_many :suits, :dependent => :destroy
  has_many :facilities, :dependent => :destroy
  accepts_nested_attributes_for :suits, :facilities, :allow_destroy => true
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :detail
	has_and_belongs_to_many :houses
  accepts_nested_attributes_for :houses
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :location, counter_cache: true

	has_one :facility
	has_one :suitability
	has_one :pricing, :dependent => :destroy
	has_many :pictures, :dependent => :destroy
	has_many :bookings, :dependent => :destroy
	has_and_belongs_to_many :suits
	has_and_belongs_to_many :facilities

	accepts_nested_attributes_for :pricing, :pictures, :facilities, :suits

	geocoded_by :address
	after_validation :geocode

	after_update :change_houses_count

	def change_activate
		if self.activated?
			self.update_attributes(:activated => false)
		else
			if self.location
				self.update_attributes(:activated => true)
			else
				return false
			end
		end
	end

	def change_houses_count
		self.location.region.change_houses_count if self.location
	end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :houses
  belongs_to :region
  accepts_nested_attributes_for :houses
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :page_config
end

app/models/page_config.rb
class PageConfig < ActiveRecord::Base
  has_many :pages
  accepts_nested_attributes_for :pages
end

app/models/period.rb
class Period < ActiveRecord::Base
	belongs_to :pricing
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :house
	mount_uploader :image, ImageUploader
	crop_uploaded :image

	def change_to_def
		self.house.pictures.each do |p|
			p.update_attribute(:default_pic, false)
		end
		self.update_attribute(:default_pic, true)
	end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :countries, :dependent => :destroy

  accepts_nested_attributes_for :countries
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
	has_many :periods, :dependent => :destroy
	has_many :costs, :dependent => :destroy
	belongs_to :house
	accepts_nested_attributes_for :periods, :costs, :allow_destroy => true
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :locations
	belongs_to :country
	accepts_nested_attributes_for :locations

  def change_houses_count
    cnt = 0
    self.locations.each do |l|
      cnt += l.houses_count
    end
    self.update_attributes(:houses_count => cnt)
  end

end

app/models/suit.rb
class Suit < ActiveRecord::Base
  belongs_to :detail
  has_and_belongs_to_many :houses
  accepts_nested_attributes_for :houses
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_house, only: [:show, :edit, :index, :create, :update, :set_default]
  respond_to :html

  def index
    @pictures = @house.pictures.order(:id)
    respond_with(@pictures)
  end

  def create
    @picture = @house.pictures.create(params[:picture].permit(:image))
    if @house.pictures.count == 1
      @picture.change_to_def
    end
  end

  def set_default
    @pic = Picture.find(params[:p])
    @pic.change_to_def
    redirect_to :back
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      flash[:notice] = "Die Änderungen wurden gespeichert!"
      redirect_to house_pictures_path
    else
      flash[:notice] = "Die Änderungen konnten nicht gespeichert werden."
      redirect_to :back
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to house_pictures_path
  end

  private

    def set_house
      @house = House.find(params[:house_id])
    end

    def picture_params
      params.require(:picture).permit(:id, :name, :house_id, :image, :default_pic, :description, :image_crop_x, :image_crop_y, :image_crop_w, :image_crop_h, :order_no, :_destroy)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/facilites_helper.rb
module FacilitesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/pictures/_picture.html.erb
<% if picture.default_pic? %>
  <div class="jumbotron picture" style="border: 1px solid black">
<% else %>
  <div class="jumbotron picture">
<% end %>
  <%= link_to house_picture_path(@house, picture), :confirm => 'Are you sure?', :method => :delete do %>
    <div class="imgtxt-right" style="height: 25px; padding: 4px;">
      <%= glyph 'remove' %>
    </div>
  <% end %>

  <%= image_tag picture.image_url(:thumb) %>

	<h4 style='text-align: center;'> <%= picture.order_no%> - #<%= picture.id %> <%= picture.name %></h4><hr style="margin: 2px;">

	<div class="row">
	  <div class="col-md-8">
		<div class="left">
		  <% if picture.default_pic? %>
		    <div style="color:darkgreen;">Default</div>
		  <% else %>
		    <%= link_to "Als Default verwenden", { :controller => 'pictures', :action => 'set_default', :p => picture.id }, { :method => :put } %>
		  <% end %>
		</div>
	  </div>
	  <div class="col-md-4 right">
	    <%= link_to "Bearbeiten", edit_house_picture_path(@house,picture), class: "btn btn-default" %>
      </div>
	</div>

</div>

app/views/pictures/create.js.erb
# encoding: UTF-8

<% if @picture.new_record? %>
    alert("Das Dateiformat wird nicht unterstützt!")
<% else %>
    $("#pictures").append("<%= j render (@picture) %>");
<% end %>

app/views/pictures/edit.html.erb
<%= simple_form_for [@house,@picture], :html => { :class => 'form-vertical' } do |f| %>

  <h2 style='text-align: center;'>Bild bearbeiten</h2><hr>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :name %>
      <%= f.input :description, label:"Beschreibung", :input_html => {:rows => 8} %>
      <%= f.input :order_no %>
    </div>
    <div class="col-md-3">
      <label class="string optional control-label" for="booking_lastname">Thumb:</label><br>
      <%= image_tag @picture.image_url(:thumb), size:"260x195" %><br><br>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">
        Thumb zuschneiden
      </button>
    </div>
    <div class="col-md-3">
      <label class="string optional control-label" for="booking_lastname">Status:</label><br>
      <% if @picture.default_pic? %>
        <div style="color:darkgreen;">Default</div>
      <% else %>
        <%= link_to "Als Default verwenden", { :controller => 'pictures', :action => 'set_default', :p => @picture.id }, { :method => :put } %>
      <% end %>

    </div>
  </div>

  <hr>

  <div class='center-block'>
    <div class='form-group text-center'>
      <%= f.button :submit, 'Änderungen speichern', :class => 'btn-primary' %> oder
      <%= link_to 'Zurück', :back, :class => 'btn btn-default' %>
    </div>
  </div>

  <%= f.file_field :image %>

<% end %>


<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Thumb zuschneiden</h4>
      </div>
      <%= simple_form_for [@house,@picture], :html => { :class => 'form-vertical' } do |f| %>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-8">Zuschneiden:<%= f.cropbox :image, version: :jumbo %></div>
            <div class="col-md-4">Vorschau:<%= f.previewbox :image, width: 260, height: 195, version: :jumbo %></div>
          </div>
        </div>
        <div class="modal-footer">
          <div class='center-block'>
            <div class='form-group text-center'>
              <%= f.button :submit, 'Speichern', :class => 'btn-primary' %> oder
              <button type="button" class="btn btn-default" data-dismiss="modal">Zurück</button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
# encoding: UTF-8

<h2>Bilder für das Haus "<%= @house.name %>":</h2>

<hr>

<div id="pictures">
  <%= render @pictures %>
</div>


<%= form_for [@house, @house.pictures.new] do |f| %>
    <%= f.label :image, "Upload" %>
    <%= f.file_field :image, multiple: true, name: "picture[image]" %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
    {%=o.name%}
  <div class="progress"><div class="progress-bar bar" role="progressbar" style="width: 0%"></div></div>
</div>
</script>
<br>
<div class="form-group">
  <%= link_to "Zurück", houses_path, :class => 'btn btn-default'  %>
</div>