config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

  get '/impressum', :to => 'pages#impressum', :as => 'impressum'
  get '/notes', :to => 'pages#notes', :as => 'notes'

  get '/h/:id', :to => 'houses#show', :as => 'house'
  put '/h/:id', :to => 'houses#update'
  patch '/h/:id', :to => 'houses#update'
  delete '/h/:id', :to => 'houses#destroy'

  devise_for :admins

  resources :houses, :except => [:show, :update, :destroy] do
      resources :pictures
      resources :bookings
  end

  put '/houses', :to => 'houses#activate'
  put '/houses/:house_id/pictures', :to => 'pictures#set_default'
  put '/houses/:house_id/bookings', :to => 'bookings#change_accepted'

  get '/list', :to => 'houses#f_index', :as => 'houses_list'

  get '/config/places', :to => 'places#edit', :as => 'edit_place'
  patch '/config/places', :to => 'places#update'
  put '/config/places', :to => 'places#update'

  get '/config/details', :to => 'details#edit', :as => 'edit_details'
  patch '/config/details', :to => 'details#update'
  put '/config/details', :to => 'details#update'

  get '/config/pages', :to => 'page_configs#edit', :as => 'edit_page_config'
  patch '/config/pages', :to => 'page_configs#update'
  put '/config/pages', :to => 'page_configs#update'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable,  and :omniauthable
  devise :database_authenticatable, :rememberable, :timeoutable, :registerable

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :house

  validates :start_date, :end_date, :firstname, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


  def change_accepted
    if self.accepted?
	    self.update_attributes(:accepted => false)
	 else
	    self.update_attributes(:accepted => true)
	 end
  end

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :pricing
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions, :dependent => :destroy
	belongs_to :place
	accepts_nested_attributes_for :regions
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_many :suits, :dependent => :destroy
  has_many :facilities, :dependent => :destroy
  accepts_nested_attributes_for :suits, :facilities, :allow_destroy => true
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :detail
	has_and_belongs_to_many :houses
  accepts_nested_attributes_for :houses
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :location, counter_cache: true

	has_one :facility
	has_one :suitability
	has_one :pricing, :dependent => :destroy
	has_many :pictures, :dependent => :destroy
	has_many :bookings, :dependent => :destroy
	has_and_belongs_to_many :suits
	has_and_belongs_to_many :facilities

	accepts_nested_attributes_for :pricing, :pictures, :facilities, :suits

	geocoded_by :address
	after_validation :geocode

	after_update :change_houses_count

	def change_activate
		if self.activated?
			self.update_attributes(:activated => false)
		else
			if self.location
				self.update_attributes(:activated => true)
			else
				return false
			end
		end
	end

	def change_houses_count
		self.location.region.change_houses_count if self.location
	end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :houses
  belongs_to :region
  accepts_nested_attributes_for :houses
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :page_config
end

app/models/page_config.rb
class PageConfig < ActiveRecord::Base
  has_many :pages
  accepts_nested_attributes_for :pages
end

app/models/period.rb
class Period < ActiveRecord::Base
	belongs_to :pricing
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :house
	mount_uploader :image, ImageUploader
	crop_uploaded :image

	def change_to_def
		self.house.pictures.each do |p|
			p.update_attribute(:default_pic, false)
		end
		self.update_attribute(:default_pic, true)
	end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :countries, :dependent => :destroy

  accepts_nested_attributes_for :countries
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
	has_many :periods, :dependent => :destroy
	has_many :costs, :dependent => :destroy
	belongs_to :house
	accepts_nested_attributes_for :periods, :costs, :allow_destroy => true
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :locations
	belongs_to :country
	accepts_nested_attributes_for :locations

  def change_houses_count
    cnt = 0
    self.locations.each do |l|
      cnt += l.houses_count
    end
    self.update_attributes(:houses_count => cnt)
  end

end

app/models/suit.rb
class Suit < ActiveRecord::Base
  belongs_to :detail
  has_and_belongs_to_many :houses
  accepts_nested_attributes_for :houses
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "Savoir" %></title>

    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <link href="http://allfont.de/allfont.css?fonts=matura-mt-script-capitals" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- GOOGLE -->
    <!-- <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  	 <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script> -->
    <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">savoir-vivre Feriendomizile</a>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if params[:action]=='home' %>"><a href="/"><%= t "nav.home" %></a></li>
            <li class="<%= 'active' if params[:controller]=='houses' %>"><a href="/list">FERIENDOMIZILE</a></li>
            <li class="<%= 'active' if params[:action]=='notes' %>"><a href="/notes">HINWEISE</a></li>
          </ul>

          <% if admin_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <%= link_to 'Admin Bereich', houses_path, :class => 'btn btn-default navbar-btn' %>
              <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'btn btn-default navbar-btn'  %>
            </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->

      </div>
    </nav>

    <div class="main">
      <div class="container outline">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <%= $browser %>
            <br>
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->
      </div>
      <div class="push"></div>
    </div>
    <br>

    <div class="footer">
      <div class="center-block">
        <div class="text-center">
          <br>
          www.savoir-vivre-feriendomizile.de by   <span style="padding-left:8px; font-family: 'Matura MT Script Capitals', arial;">savoir-vivre Feriendomizile</span><br>
          <%= link_to 'Startseite', root_url %> |
          <%= link_to 'Buchungshinweise', notes_path %> |
          <%= link_to 'Impressum', impressum_path %>
        </div>
      </div>
    </div>

	<script type="text/javascript">
  $(document).ready(function() {
      if ($('textarea.ckeditor').length > 0) {
          var data = $('textarea.ckeditor');
          $.each(data, function(i) {
              CKEDITOR.replace(data[i].id);
          });
      }
  });
</script>

  </body>
</html>

app/views/pages/_content.erb
<div class="row" style="width: 100%, margin:0;">
  <div class="col-md-12 col-sm-12">
    <div class="jumbotron color1">
      <%= @page.content.html_safe %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'content' %>

app/views/pages/impressum.html.erb
<%= render 'content' %>

app/views/pages/notes.html.erb
<%= render 'content' %>